stages:
  - build
  - deploy

variables:
  FRONTEND_IMAGE: nih-frontend

build-frontend:
  stage: build
  image: docker:24.0.5
  services:
    - name: registry.hub.docker.com/library/docker:24.0.5-dind
      alias: docker
  before_script:
  # Deploying the tools.
    - apk add -q --no-cache bash curl jq gettext
    - apk add yq --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
    - curl -f -s -LO https://storage.yandexcloud.net/yandexcloud-yc/install.sh
    - bash install.sh -i /usr/local/yandex-cloud -n
    - ln -s /usr/local/yandex-cloud/bin/yc /usr/local/bin/yc
  # Authenticating with the service account key.
    - echo "$SERVICE_ACCOUNT_PRIVATE_KEY" > key.json
    - yc config profile create sa-profile
    - yc config set service-account-key key.json
    - cat key.json | docker login --username json_key --password-stdin cr.yandex
  # Save IAM access token.
    - export IAM_TOKEN=$(yc iam create-token)
  script:
  # Building the backend image.
    - echo "Building the $FRONTEND_IMAGE"
    - docker build -f ./Dockerfile --build-arg IAM_TOKEN=$IAM_TOKEN --build-arg YANDEX_LOCKBOX_SECRET_ID=$YANDEX_LOCKBOX_SECRET_ID --build-arg SOURCE_PROVIDER=lockbox -t $YCR/$FRONTEND_IMAGE:$CI_COMMIT_BRANCH .
    - docker push $YCR/$FRONTEND_IMAGE:$CI_COMMIT_BRANCH 
  only:
    - dev
  allow_failure: false

trigger_pipeline:
  stage: deploy
  script:
    - curl --fail --request POST --form token=$BUILD_TRIGGER_TOKEN --form ref=dev "https://gitlab.com/api/v4/projects/55090371/trigger/pipeline"
  only:
    - dev
  when: on_success
  allow_failure: false
  needs: ["build-frontend"]
